
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 06 21:06:32 ART 2015
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import scanner.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Oct 06 21:06:32 ART 2015
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\005\005\000\002\005\010\000\002\007\003\000" +
    "\002\007\003\000\002\006\010\000\002\010\003\000\002" +
    "\010\003\000\002\011\005\000\002\011\003\000\002\012" +
    "\004\000\002\012\006\000\002\013\006\000\002\014\004" +
    "\000\002\014\003\000\002\015\004\000\002\015\003\000" +
    "\002\017\003\000\002\017\003\000\002\017\003\000\002" +
    "\046\002\000\002\017\005\000\002\020\004\000\002\020" +
    "\003\000\002\021\007\000\002\021\011\000\002\022\003" +
    "\000\002\022\003\000\002\025\007\000\002\027\013\000" +
    "\002\023\004\000\002\023\005\000\002\024\005\000\002" +
    "\024\003\000\002\030\003\000\002\030\006\000\002\031" +
    "\005\000\002\031\003\000\002\047\002\000\002\050\002" +
    "\000\002\051\002\000\002\052\002\000\002\053\002\000" +
    "\002\033\015\000\002\032\005\000\002\032\003\000\002" +
    "\034\003\000\002\034\003\000\002\035\005\000\002\035" +
    "\003\000\002\036\003\000\002\036\003\000\002\037\005" +
    "\000\002\037\003\000\002\040\003\000\002\040\003\000" +
    "\002\041\005\000\002\041\003\000\002\041\003\000\002" +
    "\041\003\000\002\042\006\000\002\043\003\000\002\043" +
    "\003\000\002\044\005\000\002\044\003\000\002\045\002" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\006\005\013\010\010\001\002\000\004\002" +
    "\166\001\002\000\010\002\ufffc\005\ufffc\010\ufffc\001\002" +
    "\000\010\002\ufffd\005\ufffd\010\ufffd\001\002\000\010\002" +
    "\000\005\013\010\010\001\002\000\004\041\ufff8\001\002" +
    "\000\004\041\014\001\002\000\010\002\ufffe\005\ufffe\010" +
    "\ufffe\001\002\000\004\041\ufff9\001\002\000\010\022\015" +
    "\024\017\036\016\001\002\000\006\005\013\010\024\001" +
    "\002\000\010\002\ufffb\005\ufffb\010\ufffb\001\002\000\004" +
    "\040\020\001\002\000\004\025\021\001\002\000\004\036" +
    "\022\001\002\000\010\002\ufffa\005\ufffa\010\ufffa\001\002" +
    "\000\006\023\ufff6\037\163\001\002\000\006\023\ufff5\041" +
    "\ufff8\001\002\000\004\041\160\001\002\000\004\023\030" +
    "\001\002\000\006\023\ufff3\037\ufff3\001\002\000\004\026" +
    "\032\001\002\000\010\002\ufff7\005\ufff7\010\ufff7\001\002" +
    "\000\022\004\uffbb\011\uffbb\022\uffbb\026\uffbb\027\uffbb\036" +
    "\uffbb\040\uffbb\041\uffbb\001\002\000\022\004\uffbb\011\uffbb" +
    "\022\uffbb\026\uffbb\027\uffbb\036\uffbb\040\uffbb\041\uffbb\001" +
    "\002\000\022\004\uffee\011\uffee\022\uffee\026\uffee\027\uffee" +
    "\036\uffee\040\uffee\041\uffee\001\002\000\022\004\047\011" +
    "\043\022\042\026\032\027\063\036\062\040\051\041\050" +
    "\001\002\000\022\004\uffef\011\uffef\022\uffef\026\uffef\027" +
    "\uffef\036\uffef\040\uffef\041\uffef\001\002\000\022\004\uffec" +
    "\011\uffec\022\uffec\026\uffec\027\uffec\036\uffec\040\uffec\041" +
    "\uffec\001\002\000\004\007\uffe2\001\002\000\022\004\uffed" +
    "\011\uffed\022\uffed\026\uffed\027\uffed\036\uffed\040\uffed\041" +
    "\uffed\001\002\000\010\022\042\040\051\041\050\001\002" +
    "\000\004\022\152\001\002\000\004\007\uffe1\001\002\000" +
    "\026\004\uffea\006\uffea\007\uffea\011\uffea\022\uffea\026\uffea" +
    "\027\uffea\036\uffea\040\uffea\041\uffea\001\002\000\030\013" +
    "\uffc7\014\uffc7\015\uffc7\016\uffc7\017\uffc7\020\uffc7\023\uffc7" +
    "\025\uffc7\031\uffc7\036\uffc7\037\uffc7\001\002\000\004\022" +
    "\144\001\002\000\036\013\uffda\014\uffda\015\uffda\016\uffda" +
    "\017\uffda\020\uffda\021\uffda\022\131\023\uffda\024\132\025" +
    "\uffda\031\uffda\036\uffda\037\uffda\001\002\000\030\013\uffc1" +
    "\014\uffc1\015\uffc1\016\uffc1\017\uffc1\020\uffc1\023\uffc1\025" +
    "\uffc1\031\uffc1\036\uffc1\037\uffc1\001\002\000\004\036\130" +
    "\001\002\000\030\013\uffcb\014\uffcb\015\uffcb\016\uffcb\017" +
    "\104\020\103\023\uffcb\025\uffcb\031\uffcb\036\uffcb\037\uffcb" +
    "\001\002\000\020\013\112\014\107\023\uffd7\025\uffd7\031" +
    "\113\036\uffd7\037\uffd7\001\002\000\024\013\uffcf\014\uffcf" +
    "\015\076\016\100\023\uffcf\025\uffcf\031\uffcf\036\uffcf\037" +
    "\uffcf\001\002\000\012\023\uffdb\025\uffdb\036\uffdb\037\uffdb" +
    "\001\002\000\026\004\uffeb\006\uffeb\007\uffeb\011\uffeb\022" +
    "\uffeb\026\uffeb\027\uffeb\036\uffeb\040\uffeb\041\uffeb\001\002" +
    "\000\026\004\uffe9\006\uffe9\007\uffe9\011\uffe9\022\uffe9\026" +
    "\uffe9\027\uffe9\036\uffe9\040\uffe9\041\uffe9\001\002\000\004" +
    "\007\uffe8\001\002\000\026\004\uffe5\006\uffe5\007\uffe5\011" +
    "\uffe5\022\uffe5\026\uffe5\027\uffe5\036\uffe5\040\uffe5\041\uffe5" +
    "\001\002\000\034\002\ufff0\004\ufff0\005\ufff0\006\ufff0\007" +
    "\ufff0\010\ufff0\011\ufff0\022\ufff0\026\ufff0\027\ufff0\036\ufff0" +
    "\040\ufff0\041\ufff0\001\002\000\030\013\uffc2\014\uffc2\015" +
    "\uffc2\016\uffc2\017\uffc2\020\uffc2\023\uffc2\025\uffc2\031\uffc2" +
    "\036\uffc2\037\uffc2\001\002\000\032\013\uffc3\014\uffc3\015" +
    "\uffc3\016\uffc3\017\uffc3\020\uffc3\021\066\023\uffc3\025\uffc3" +
    "\031\uffc3\036\uffc3\037\uffc3\001\002\000\010\022\042\040" +
    "\051\041\050\001\002\000\012\023\uffdc\025\uffdc\036\uffdc" +
    "\037\uffdc\001\002\000\004\007\071\001\002\000\012\022" +
    "\042\036\074\040\051\041\050\001\002\000\026\004\uffe7" +
    "\006\uffe7\007\uffe7\011\uffe7\022\uffe7\026\uffe7\027\uffe7\036" +
    "\uffe7\040\uffe7\041\uffe7\001\002\000\004\036\075\001\002" +
    "\000\026\004\uffde\006\uffde\007\uffde\011\uffde\022\uffde\026" +
    "\uffde\027\uffde\036\uffde\040\uffde\041\uffde\001\002\000\026" +
    "\004\uffdd\006\uffdd\007\uffdd\011\uffdd\022\uffdd\026\uffdd\027" +
    "\uffdd\036\uffdd\040\uffdd\041\uffdd\001\002\000\010\022\uffca" +
    "\040\uffca\041\uffca\001\002\000\010\022\042\040\051\041" +
    "\050\001\002\000\010\022\uffc9\040\uffc9\041\uffc9\001\002" +
    "\000\030\013\uffc3\014\uffc3\015\uffc3\016\uffc3\017\uffc3\020" +
    "\uffc3\023\uffc3\025\uffc3\031\uffc3\036\uffc3\037\uffc3\001\002" +
    "\000\030\013\uffcc\014\uffcc\015\uffcc\016\uffcc\017\104\020" +
    "\103\023\uffcc\025\uffcc\031\uffcc\036\uffcc\037\uffcc\001\002" +
    "\000\010\022\uffc5\040\uffc5\041\uffc5\001\002\000\010\022" +
    "\uffc6\040\uffc6\041\uffc6\001\002\000\010\022\042\040\051" +
    "\041\050\001\002\000\030\013\uffc8\014\uffc8\015\uffc8\016" +
    "\uffc8\017\uffc8\020\uffc8\023\uffc8\025\uffc8\031\uffc8\036\uffc8" +
    "\037\uffc8\001\002\000\010\022\uffcd\040\uffcd\041\uffcd\001" +
    "\002\000\010\022\042\040\051\041\050\001\002\000\010" +
    "\022\042\040\051\041\050\001\002\000\010\022\uffce\040" +
    "\uffce\041\uffce\001\002\000\004\030\uffd6\001\002\000\004" +
    "\030\115\001\002\000\004\032\uffd5\001\002\000\004\032" +
    "\117\001\002\000\004\033\uffd4\001\002\000\004\033\121" +
    "\001\002\000\004\034\uffd3\001\002\000\004\034\123\001" +
    "\002\000\004\035\uffd2\001\002\000\004\035\125\001\002" +
    "\000\010\022\uffd1\040\uffd1\041\uffd1\001\002\000\016\013" +
    "\112\014\107\023\uffd8\025\uffd8\036\uffd8\037\uffd8\001\002" +
    "\000\024\013\uffd0\014\uffd0\015\076\016\100\023\uffd0\025" +
    "\uffd0\031\uffd0\036\uffd0\037\uffd0\001\002\000\026\004\uffe6" +
    "\006\uffe6\007\uffe6\011\uffe6\022\uffe6\026\uffe6\027\uffe6\036" +
    "\uffe6\040\uffe6\041\uffe6\001\002\000\012\022\042\023\uffbb" +
    "\040\051\041\050\001\002\000\010\022\042\040\051\041" +
    "\050\001\002\000\004\025\134\001\002\000\032\013\uffd9" +
    "\014\uffd9\015\uffd9\016\uffd9\017\uffd9\020\uffd9\021\uffd9\023" +
    "\uffd9\025\uffd9\031\uffd9\036\uffd9\037\uffd9\001\002\000\006" +
    "\023\uffbf\037\142\001\002\000\004\023\uffbe\001\002\000" +
    "\006\023\uffbc\037\uffbc\001\002\000\004\023\141\001\002" +
    "\000\030\013\uffc0\014\uffc0\015\uffc0\016\uffc0\017\uffc0\020" +
    "\uffc0\023\uffc0\025\uffc0\031\uffc0\036\uffc0\037\uffc0\001\002" +
    "\000\010\022\042\040\051\041\050\001\002\000\006\023" +
    "\uffbd\037\uffbd\001\002\000\010\022\042\040\051\041\050" +
    "\001\002\000\004\023\146\001\002\000\020\004\047\011" +
    "\043\022\042\026\032\036\062\040\051\041\050\001\002" +
    "\000\026\004\uffe4\006\150\007\uffe4\011\uffe4\022\uffe4\026" +
    "\uffe4\027\uffe4\036\uffe4\040\uffe4\041\uffe4\001\002\000\020" +
    "\004\047\011\043\022\042\026\032\036\062\040\051\041" +
    "\050\001\002\000\026\004\uffe3\006\uffe3\007\uffe3\011\uffe3" +
    "\022\uffe3\026\uffe3\027\uffe3\036\uffe3\040\uffe3\041\uffe3\001" +
    "\002\000\010\022\042\040\051\041\050\001\002\000\004" +
    "\023\154\001\002\000\020\004\047\011\043\022\042\026" +
    "\032\036\062\040\051\041\050\001\002\000\004\007\uffe0" +
    "\001\002\000\004\023\157\001\002\000\030\013\uffc4\014" +
    "\uffc4\015\uffc4\016\uffc4\017\uffc4\020\uffc4\023\uffc4\025\uffc4" +
    "\031\uffc4\036\uffc4\037\uffc4\001\002\000\010\023\ufff2\024" +
    "\161\037\ufff2\001\002\000\004\025\162\001\002\000\006" +
    "\023\ufff1\037\ufff1\001\002\000\006\005\013\010\010\001" +
    "\002\000\006\023\ufff4\037\ufff4\001\002\000\010\002\uffff" +
    "\005\uffff\010\uffff\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\016\002\003\003\006\004\011\005\005\006" +
    "\004\007\010\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\004\164\005\005\006\004\007" +
    "\010\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\007" +
    "\024\010\025\011\022\012\026\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\030\001\001\000\002\001\001\000\006\014\032\045\033" +
    "\001\001\000\010\015\034\016\035\045\036\001\001\000" +
    "\002\001\001\000\040\013\044\017\040\020\056\021\057" +
    "\022\060\024\051\025\037\026\043\030\064\031\055\032" +
    "\053\035\054\037\052\041\045\042\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\024\155\030\064\031\055\032\053\035\054" +
    "\037\052\041\045\042\063\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\040\104\001\001\000\006\033\110\034\107" +
    "\001\001\000\004\036\076\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\046\067\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\024\066\030\064\031\055\032\053" +
    "\035\054\037\052\041\045\042\063\001\001\000\002\001" +
    "\001\000\004\023\071\001\001\000\022\024\072\030\064" +
    "\031\055\032\053\035\054\037\052\041\045\042\063\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\030\100\037" +
    "\101\041\045\042\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\040\104\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\030\100\041\105\042\063\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\030\100\035" +
    "\126\037\052\041\045\042\063\001\001\000\016\030\100" +
    "\032\125\035\054\037\052\041\045\042\063\001\001\000" +
    "\002\001\001\000\004\047\113\001\001\000\002\001\001" +
    "\000\004\050\115\001\001\000\002\001\001\000\004\051" +
    "\117\001\001\000\002\001\001\000\004\052\121\001\001" +
    "\000\002\001\001\000\004\053\123\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\034\107\001\001\000\004" +
    "\036\076\001\001\000\002\001\001\000\030\024\136\030" +
    "\064\031\055\032\053\035\054\037\052\041\045\042\063" +
    "\043\137\044\134\045\135\001\001\000\022\024\132\030" +
    "\064\031\055\032\053\035\054\037\052\041\045\042\063" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\024\142\030\064\031\055\032" +
    "\053\035\054\037\052\041\045\042\063\001\001\000\002" +
    "\001\001\000\022\024\144\030\064\031\055\032\053\035" +
    "\054\037\052\041\045\042\063\001\001\000\002\001\001" +
    "\000\040\013\044\017\146\020\056\021\057\022\060\024" +
    "\051\025\037\026\043\030\064\031\055\032\053\035\054" +
    "\037\052\041\045\042\063\001\001\000\002\001\001\000" +
    "\040\013\044\017\150\020\056\021\057\022\060\024\051" +
    "\025\037\026\043\030\064\031\055\032\053\035\054\037" +
    "\052\041\045\042\063\001\001\000\002\001\001\000\022" +
    "\024\152\030\064\031\055\032\053\035\054\037\052\041" +
    "\045\042\063\001\001\000\002\001\001\000\040\013\044" +
    "\017\154\020\056\021\057\022\060\024\051\025\037\026" +
    "\043\030\064\031\055\032\053\035\054\037\052\041\045" +
    "\042\063\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\007\024\012\163\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public void report_error(String message, Object info) {
    	    StringBuilder m = new StringBuilder("Error");
        	if (info instanceof java_cup.runtime.Symbol) {
            	java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
            if (s.left >= 0) {                
                m.append(" en linea "+(s.left+1));
                if (s.right >= 0)
                    m.append(", columna "+(s.right+1));
            }
        }
        m.append(" : "+message);
        //System.err.println(m);
    }
   
    /* Cuando se encuentra un error de donde el sistema no puede
        recuperarse, se lanza un error fatal. Se despliega el mensaje
        de error y se finaliza la ejecucion. */
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        //System.exit(1);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // empty ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("empty",35, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // arg_list ::= expression 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // arg_list ::= arg_list COMA expression 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("arg_list",34, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // args ::= empty 
            {
              Object RESULT =null;
		
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // args ::= arg_list 
            {
              Object RESULT =null;
		
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("args",33, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // call ::= ID PARENT_IZQ args PARENT_DER 
            {
              Object RESULT =null;
		
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("call",32, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // exp ::= NUM 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // exp ::= call 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // exp ::= var 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= PARENT_IZQ expression PARENT_DER 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("exp",31, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // powop ::= EXPONENCIACION_2 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("powop",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // powop ::= EXPONENCIACION_1 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("powop",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // factor ::= exp 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= factor powop exp 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // mulop ::= DIVISION 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mulop",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // mulop ::= MULTIPLICACION 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("mulop",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // term ::= factor 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // term ::= term mulop factor 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("term",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // addop ::= RESTA 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("addop",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // addop ::= SUMA 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("addop",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // additive_expression ::= term 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("additive_expression",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // additive_expression ::= additive_expression addop term 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("additive_expression",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // relop ::= MENIGUAL NT$1 MENOR NT$2 MAYOR NT$3 MAYIGUAL NT$4 IGUALIGUAL NT$5 DISTINTO 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("relop",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // NT$5 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$5",41, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // NT$4 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$4",40, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // NT$3 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$3",39, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // NT$2 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$2",38, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // NT$1 ::= 
            {
              Object RESULT =null;

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$1",37, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // simple_expression ::= additive_expression 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // simple_expression ::= additive_expression relop additive_expression 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("simple_expression",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // var ::= ID CORCH_IZQ expression CORCH_DER 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // var ::= ID 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expression ::= simple_expression 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expression ::= var ASSIGN expression 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // return_stmt ::= RETURN expression PUNTOCOMA 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_stmt",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // return_stmt ::= RETURN PUNTOCOMA 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("return_stmt",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // for_stmt ::= FOR PARENT_IZQ expression COMA expression COMA expression PARENT_DER statement 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // while_stmt ::= WHILE PARENT_IZQ expression PARENT_DER statement 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_stmt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // iteration_stmt ::= do_while_stmt 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // iteration_stmt ::= while_stmt 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("iteration_stmt",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // selection_stmt ::= IF PARENT_IZQ expression PARENT_DER statement ELSE statement 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // selection_stmt ::= IF PARENT_IZQ expression PARENT_DER statement 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("selection_stmt",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expression_stmt ::= PUNTOCOMA 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expression_stmt ::= expression PUNTOCOMA 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expression_stmt",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // statement ::= iteration_stmt NT$0 return_stmt 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$0 ::= 
            {
              Object RESULT =null;

                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",36, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // statement ::= selection_stmt 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // statement ::= compound_stmt 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // statement ::= expression_stmt 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // statement_list ::= empty 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // statement_list ::= statement_list statement 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("statement_list",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // local_declarations ::= empty 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // local_declarations ::= local_declarations var_declarations 
            {
              Object RESULT =null;
		
                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("local_declarations",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // compound_stmt ::= LLAVE_IZQ local_declarations statement_list LLAVE_DER 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("compound_stmt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param ::= type_specifier ID CORCH_IZQ CORCH_DER 
            {
              Object RESULT =null;
		
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param ::= type_specifier ID 
            {
              Object RESULT =null;
		
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // param_list ::= param 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // param_list ::= param_list COMA param 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_list",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // params ::= VOID 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= param_list 
            {
              Object RESULT =null;
		
                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // fun_declaration ::= type_specifier ID PARENT_IZQ params PARENT_DER compound_stmt 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("fun_declaration",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // type_specifier ::= VOID 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // type_specifier ::= INT 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("type_specifier",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // var_declaration ::= type_specifier ID CORCH_IZQ NUM CORCH_DER PUNTOCOMA 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // var_declaration ::= type_specifier ID PUNTOCOMA 
            {
              Object RESULT =null;
		
                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("var_declaration",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaration ::= fun_declaration 
            {
              Object RESULT =null;
		
                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaration ::= var_declaration 
            {
              Object RESULT =null;
		

                        
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // declaration_list ::= declaration 
            {
              Object RESULT =null;
		

                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // declaration_list ::= declaration_list declaration 
            {
              Object RESULT =null;
		

                            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaration_list",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= declaration_list 
            {
              Object RESULT =null;
		

                    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

