
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 23 11:44:44 ART 2015
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXPONENCIACION_2 = 14;
  public static final int EXPONENCIACION_1 = 13;
  public static final int IGUALIGUAL = 26;
  public static final int MENOR = 22;
  public static final int MULTIPLICACION = 11;
  public static final int ELSE = 4;
  public static final int INT = 3;
  public static final int PARENT_IZQ = 16;
  public static final int WHILE = 7;
  public static final int DIVISION = 12;
  public static final int SUMA = 9;
  public static final int MAYIGUAL = 25;
  public static final int PARENT_DER = 17;
  public static final int RETURN = 5;
  public static final int IF = 2;
  public static final int ID = 31;
  public static final int NUM = 30;
  public static final int COMA = 29;
  public static final int MENIGUAL = 23;
  public static final int DISTINTO = 27;
  public static final int MAYOR = 24;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int LLAVE_IZQ = 20;
  public static final int CORCH_IZQ = 18;
  public static final int PUNTOCOMA = 28;
  public static final int LLAVE_DER = 21;
  public static final int CORCH_DER = 19;
  public static final int FOR = 8;
  public static final int VOID = 6;
  public static final int RESTA = 10;
}

